### ISSUE TITLE
importation and integration into eclipse

### ISSUE THREAD

**Issue by SyCode7** [haproxyhq/backend#1]
Hi, many thanks for your efforts in this project. I am trying to import the backend module into eclipse. Will this be possible or i need to use a proper spring environment ? Thanks.

**Comment by buettner123** [comment]
Hi, you should be able to import it as a maven project into eclipse without problems.

**Comment by buettner123** [comment]
I'm closing this issue for now. You can reopen it, if you have problems importing it.

**Comment by SyCode7** [comment]
Thanks for the quick response.
