### ISSUE TITLE
InvalidSchema: No connection adapters were found for '192.168.242.128:8080/agents/test/

### ISSUE THREAD

**Issue by SyCode7** [haproxyhq/backend#2]
Hi,

I have installed the agent in my server, and installed also mongodb, postgress and mosquitto as stated in the readme. I also ran the setup file.... but I am getting the error `InvalidSchema: No connection adapters were found for '192.168.242.128:8080/agents/test/` after running the agent script. Is there anything I need to do ?

**Comment by SyCode7** [comment]
Hi ,  I have been able to resolve this above mentioned challenge, it was owing to some incomplete configurations/installations on my part. I am trying to log in now to the web ui, I suppose the email address and password I configured in the backend's application.properties file should work but it logging in still fails. BTW, do I need the UI to modify the haproxy settings ? Thanks.

**Comment by buettner123** [comment]
I'm glad that you could solve your problem on your own. To login to the web-ui please read https://github.com/haproxyhq/frontend#haproxyhqfrontendinstall--use and use the user pointed out there for initial login.
You can use whatever you want for modifying the settings (postman for example will work as well, as long as you send the right json to the backend). Only the backend and the agent are essential to use this.

closing this issue as it is solved
